name: sysfoo-demo
on:
  push:
    branches:
      - 'master'
jobs:
  sysfoo-job:
    runs-on: ubuntu-latest
    steps:
     - name: Hello World
       run: echo "Welcome to Training"
     - name: code checkout
       uses: actions/checkout@v6
     - name: test
       run: mvn test
     - name: clean package
       run: mvn clean
     - name: package
       run: mvn package
     - name: view files
       run: ls -ltr target
     - name: upload artifact
       uses: action/upload-artifact@v4
       with:
         name: sysfoo
         path: target/**.war
       
